# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_auto_20161102_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='salas.Tag'),
        ),
    ]
